#!/usr/bin/env ruby
require 'rubygems'
require "daemons"
require 'yaml'
require 'erb'
#require 'active_support'

options = {
    :dir_mode   => :script,
    :dir        => '../../log',
    :multiple   => false,
    :backtrace  => true,
    :monitor    => true
  }
Daemons.run File.dirname(__FILE__) + '/processor.rb', options