# This configuration controller was generated by the rails_configu_model generator
# 
# This controller provides an interface to quickly edit the values in the configurations table.
# See Configuration for more details on the system configuration.
#

class ConfigurationController < ApplicationController

  before_filter :find_configuration
  
  
  # Simply redirect to the edit action
  def index
    edit
    render :action=> "edit"
  end
  

  # Shows the page to edit the configuration variables.
  def edit
  end
  
  
  # Saves the posted data to the configurations table via the standard
  # Rails mass-assignment update approach.
  def update

    if @configuration.update_attributes(params[:configuration])
      flash[:notice] = 'Your system configuration was successfully updated.'
      redirect_to :action => 'edit'
    else
      render :action=>"edit"
    end
  end

  
  protected
  
  # Before filter to load the configuration data.
  def find_configuration
     @configuration =  Configuration.load
  end
  
end
